### PR TITLE
Added classifier by globalId

### PR DESCRIPTION
**Pull request by MadsHolten**
### Description

When storing additional entity data in an external database it is common to use globalIds since these are persistent across different versions of the same IFC model. Therefore it is useful to have a classifier that retrieves fragments based on globalId.

### Additional context

Tested locally with two models loaded and it works.

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following:

- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Follow the [Conventional Commits v1.0.0](https://www.conventionalcommits.org/en/v1.0.0/) standard for PR naming (e.g. `feat(examples): add hello-world example`).
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by MadsHolten** [comment]
Another option could be to make the saveItem() method public so the FragmentClassifier can easily be extended with custom classifiers.

Example:
```typescript
export class ExtendedClassifier extends FragmentClassifier{

    byGlobalId(group: FragmentsGroup){
        const properties = group.properties;
        if (!properties)
          throw new Error("To group by GlobalId, properties are needed");
        for (const expressID in group.data) {
            if (group.properties === undefined) continue;
            const globalId = group.properties[expressID]?.GlobalId?.value;
            if (globalId === undefined) continue;
            this.saveItem(group, "globalIds", globalId, expressID);
        }
    }

}
```

**Comment by HoyosJuan** [comment]
Hey @MadsHolten! Correct if I'm wrong, but this would create an object with 1:1 relation, right? For example:

{
"1266e70f-ce9b-43ed-8afd-417a0fce1629": ["123"],
"111deec7-1446-4433-9001-3cde80ecd543": ["543"],
.
.
.
}

**Comment by K1vs** [comment]
Great idea, I also made such a classifier.  But, unfortunately, it does not work on large models.  The current implementation of the find method is too slow for the number of categories such a classifier produces. For my medium size model it takes about 5min to build FragmentTree based on globalId classification.

**Comment by agviegas** [comment]
Hey @MadsHolten now FragmentGroups have a `globalToExpressID` map that allows to easily work with global IDs. So you can map global IDs to expressIDs, and then work normally with the rest of the API. Closing this!

**Pull request closed without merging**
