### PR TITLE
feat(function): add createPhysicalEdges

### PR DESCRIPTION
**Pull request by Curiosit**
Function `createPhysicalEdges` creates edges by recreating mesh edges out of instancedMeshes

### Description

This function creates physical edges as `THREE.LineSegments`

image

### Additional context

There is also an example file included in the pull request

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [X] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following:

- [X] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [X] Follow the [Conventional Commits v1.0.0](https://www.conventionalcommits.org/en/v1.0.0/) standard for PR naming (e.g. `feat(examples): add hello-world example`).
- [X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by Curiosit** [comment]
I have observed the file structure slightly changed. I proposed to put the function into a different file.

**Comment by HoyosJuan** [comment]
Hi @Mateusz!

In one of the most recent internal meetings we had, we disscused about the way to go with the library. Long story short, we have decided to accelerate the development of That Open Platform which includes  the store, a place where developers like you can upload their tools to share with other people.

So, because of that, we are going to keep the repository functionalities as tight as possible with the best performance we can. We have reviewed your code and it's great! But for medium size and big models it consumes much more memory because of the draw calls. Also, it would be difficult to hide the edges when individual elements from fragments are hidden without the need to recreate the edges again, which involves more drawcalls. Don't get me wrong, it's just that the current solution is more performant (although we know it could be further improved!).

My suggestion? To make a standalone tool out of this and post it in [Share Your Wins](https://people.thatopen.com/c/share-your-wins/) so other people can use it! One the store launches, you can upload your tool there and hopefully even make money with it 🙂.

Thanks for your participation, it means a lot.

**Comment by Curiosit** [comment]
Thanks for the answer @HoyosJuan - looking forward to the platform, for sharing specific tools!

**Comment by HoyosJuan** [comment]
Great! Don't forget to convert this functionality in a tool (just as done in the master)!

**Pull request closed without merging**
